services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - feed-network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    volumes:
      - ../src:/repo/src
      - plugins_builtin:/repo/plugins/builtin
      - /repo/src/Feed.WebApi/obj
      - /repo/src/Feed.WebApi/bin
      - /repo/src/Feed.Application/obj
      - /repo/src/Feed.Application/bin
      - /repo/src/Feed.Domain/obj
      - /repo/src/Feed.Domain/bin
      - /repo/src/Feed.Persistence/obj
      - /repo/src/Feed.Persistence/bin
      - /repo/src/Feed.Security/obj
      - /repo/src/Feed.Security/bin
      - /repo/src/Feed.Shared/obj
      - /repo/src/Feed.Shared/bin
      - /repo/src/Feed.Email/obj
      - /repo/src/Feed.Email/bin
      - /repo/src/Feed.Plugin.Abstractions/obj
      - /repo/src/Feed.Plugin.Abstractions/bin
      - /repo/src/Feed.Plugin.Host/obj
      - /repo/src/Feed.Plugin.Host/bin
      - /repo/src/Feed.Vk/obj
      - /repo/src/Feed.Vk/bin
      - /repo/src/Feed.Telegram/obj
      - /repo/src/Feed.Telegram/bin
    depends_on:
      - db
      - plugins-watch
    networks:
      - feed-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: true

      # Все переменные берутся из .env файла
      ConnectionStrings__PostgresDbConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      AccessTokenOptions__JwtOptions__SecretKey: ${AccessTokenOptions__JwtOptions__SecretKey}
      AccessTokenOptions__JwtOptions__ExpiresHours: ${AccessTokenOptions__JwtOptions__ExpiresHours}
      EmailProviderOptions__Host: ${EmailProviderOptions__Host}
      EmailProviderOptions__Port: ${EmailProviderOptions__Port}
      EmailProviderOptions__EnableSsl: ${EmailProviderOptions__EnableSsl}
      EmailProviderOptions__Credentials__Address: ${EmailProviderOptions__Credentials__Address}
      EmailProviderOptions__Credentials__Password: ${EmailProviderOptions__Credentials__Password}
      PluginOptions__Directories__0: "/repo/plugins/builtin"

  plugins-watch:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: plugins-development
    volumes:
      - ../src:/repo/src
      - plugins_builtin:/repo/plugins/builtin
    networks:
      - feed-network

volumes:
  pg_data:
  plugins_builtin:

networks:
  feed-network:
    driver: bridge